import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { platform } from './platform';
import './styles.css';
import './paper.css';
import './desktop.css';
import './motion.css';
document.documentElement.dataset.platform = platform;
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
