import {beforeEach,describe,expect,it} from "vitest";
import {renderToStaticMarkup} from "react-dom/server";
import {bridge,preview,tagDisplayName} from "./data";
import {TagList} from "./components/LibraryViews";
import {Post} from "./components/Thoughts";
import {TagSharingSettings} from "./components/Sharing";
beforeEach(()=>preview.reset(true));
async function tag(name:string){await bridge.saveTag({name,type:"checklist"});return (await bridge.library()).tags.filter(t=>t.name===name).at(-1)!;}
describe("shared hashtags",()=>{
 it("keeps a same-name private tag distinct and requires explicit inline selection",async()=>{const shared=await tag("Movies");await bridge.startTagSharing({tagId:shared.id});const privateTag=await tag("Movies");const tags=(await bridge.library()).tags;expect(tags).toHaveLength(2);expect(tagDisplayName(tags.find(t=>t.id===shared.id)!,tags)).toContain("Shared");expect(tagDisplayName(privateTag,tags)).toContain("Private");const {draft}=await bridge.getDraft({});expect(()=>preview.save({...draft,text:"Watch #Movies",tagIds:[]})).toThrow(/ambiguous|Choose/i);const id=preview.save({...draft,text:"Watch #Movies",tagIds:[shared.id]});expect((await bridge.getEntry({id})).entry!.tagIds).toEqual([shared.id]);});
 it("rejects a second shared hashtag while retaining the draft",async()=>{const a=await tag("Movies"),b=await tag("Books");await bridge.startTagSharing({tagId:a.id});await bridge.startTagSharing({tagId:b.id});const {draft}=await bridge.getDraft({});await bridge.updateDraft({profileKey:draft.profileKey,text:"Keep my draft",tagIds:[a.id,b.id]});await expect(bridge.commitDraft({draft:{...draft,text:"Keep my draft",tagIds:[a.id,b.id]}})).rejects.toThrow(/only one shared/);expect((await bridge.getDraft({})).draft.text).toBe("Keep my draft");expect((await bridge.queryEntries({})).entries).toHaveLength(0);});
 it("renders shared and Checklist indicators together and explains the sharing boundary",async()=>{const shared=await tag("Movies");await bridge.startTagSharing({tagId:shared.id});const tags=(await bridge.library()).tags;const list=renderToStaticMarkup(<TagList tags={tags} query="" open={()=>{}} edit={()=>{}}/>);expect(list).toContain("Shared");expect(list).toContain("Checklist");const settings=renderToStaticMarkup(<TagSharingSettings expanded tag={tags[0]} changed={async()=>{}} close={()=>{}}/>);expect(settings).toContain("Shared hashtag");expect(settings).toContain("Waiting for members");const {draft}=await bridge.getDraft({});const id=preview.save({...draft,text:"Arrival",tagIds:[shared.id]});const entry=(await bridge.getEntry({id})).entry!;const post=renderToStaticMarkup(<Post entry={entry} tags={tags} complete={()=>{}} completionPending={false} star={()=>{}} edit={()=>{}} remove={()=>{}} openTag={()=>{}} report={()=>{}}/>);expect(post).toContain("Shared");expect(post).toContain(">Checklist</span>");expect(post).toContain('role="checkbox"');});
});
